default_attributes = {
    'time': {'axis': 'T',
             'long_name': 'Timestamp',
             'calendar': 'gregorian',
             'standard_name': 'time',
             'units': 'seconds since 1970-01-01T00:00:00Z',
             'valid_max': 2147483647,
             'valid_min': 0},
    'latitude': {'axis': 'Y',
                 'long_name': 'Latitude',
                 'precision': 5,
                 'standard_name': 'latitude',
                 'units': 'degree_north',
                 'valid_max': 90.0,
                 'valid_min': -90.0},
    'longitude': {'axis': 'Y',
                  'long_name': 'Longitude',
                  'precision': 5,
                  'standard_name': 'longitude',
                  'units': 'degree_east',
                  'valid_max': 180.0,
                  'valid_min': -180.0},
    'depth_raw': {'axis': 'Z',
                  'long_name': 'CTD Depth',
                  'precision': 2,
                  'observation_type': 'measured',
                  'positive': 'down',
                  'reference_datum': 'sea-surface',
                  'standard_name': 'sea_water_depth',
                  'units': 'm',
                  'valid_max': 2000.0,
                  'valid_min': 0.0,
                  'comment': 'Calculated from pressure and latitude'},
    'pressure_raw': {'axis': 'Z',
                     'long_name': 'CTD Pressure',
                     'precision': 2,
                     'observation_type': 'measured',
                     'positive': 'down',
                     'reference_datum': 'sea-surface',
                     'standard_name': 'sea_water_pressure',
                     'units': 'decibar',
                     'valid_max': 2000.0,
                     'valid_min': 0.0,
                     'comment': 'Converted from bar to decibar'},
    'temperature_raw': {'long_name': 'Raw Temperature',
                        'precision': 2,
                        'observation_type': 'measured',
                        'standard_name': 'sea_water_temperature',
                        'units': 'degrees_C',
                        'valid_max': 40.0,
                        'valid_min': -5.0},
    'conductivity_raw': {'long_name': 'Raw Conductivity',
                         'precision': 2,
                         'observation_type': 'measured',
                         'standard_name': 'sea_water_electrical_conductivity',
                         'units': 'S m-1',
                         'valid_max': 10.0,
                         'valid_min': 0.0},
    'practical_salinity_raw': {'long_name': 'Raw Practical Salinity',
                     'precision': 2,
                     'observation_type': 'calculated',
                     'standard_name': 'sea_water_practical_salinity',
                     'units': '1',
                     'valid_max': 40.0,
                     'valid_min': 0.0},
    'density_raw': {'long_name': 'Raw Density',
                    'precision': 2,
                    'observation_type': 'calculated',
                    'standard_name': 'sea_water_density',
                    'units': 'kg m-3',
                    'valid_max': 1040.0,
                    'valid_min': 1015.0},
    'profile': {'long_name': 'Profile Number',
                'comment': 'Sequential profile number',
                'units': '1',
                'valid_min': 1,
                'valid_max': 100000},
    'profile_time': {'long_name': 'Profile Time',
                     'comment': 'Timestamp of the mid-point of the profile',
                     'units': 'seconds since 1970-01-01T00:00:00Z',
                     'standard_name': 'time'},
    'sound_speed': {'long_name': 'Sound Velocity',
                    'observation_type': 'calculated',
                    'precision': 2,
                    'standard_name': 'speed_of_sound_in_sea_water',
                    'units': 'm s-1',
                    'valid_max': 1460.0,
                    'valid_min': 1560.0}
}
